# Generated by Django 2.0.6 on 2018-06-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20180627_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Guild'),
            preserve_default=False,
        ),
    ]
