# Generated by Django 2.0.6 on 2018-06-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_player_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
