# Generated by Django 2.0.6 on 2018-07-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_guild_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('char1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char1', to='manager.Character')),
                ('char2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char2', to='manager.Character')),
                ('char3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char3', to='manager.Character')),
                ('char4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char4', to='manager.Character')),
                ('char5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char5', to='manager.Character')),
            ],
        ),
    ]
