# Generated by Django 2.0.6 on 2018-07-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_squad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['player_name']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['character__name']},
        ),
        migrations.AlterField(
            model_name='squad',
            name='category',
            field=models.CharField(choices=[('other', 'Другое'), ('arena', 'Арена'), ('raid-rancor', 'Рейд: Ранкор'), ('raid-aat', 'Рейд: AAT'), ('raid-sith', 'Рейд: Триумвират ситхов'), ('lstb', 'Светлые территориальные битвы'), ('dstb', 'Темные территориальные битвы'), ('tw-offense', 'Войны гильдий: Атака'), ('tw-defense', 'Войны шильдий: Защита')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='squad',
            name='char1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char1', to='manager.Character', verbose_name='Character 1'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='char2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char2', to='manager.Character', verbose_name='Character 2'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='char3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char3', to='manager.Character', verbose_name='Character 3'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='char4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char4', to='manager.Character', verbose_name='Character 4'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='char5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char5', to='manager.Character', verbose_name='Character 5'),
        ),
    ]
