# Generated by Django 2.0.6 on 2018-07-06 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180706_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squad',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='squad',
            name='total_useful',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='char1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char1', to='manager.Character', verbose_name='Character 1'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='char2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char2', to='manager.Character', verbose_name='Character 2'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='char3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char3', to='manager.Character', verbose_name='Character 3'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='char4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char4', to='manager.Character', verbose_name='Character 4'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='char5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char5', to='manager.Character', verbose_name='Character 5'),
        ),
    ]
