# Generated by Django 2.0.6 on 2018-07-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20180707_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Character')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Player')),
            ],
            options={
                'ordering': ['character__name'],
            },
        ),
    ]
