# Generated by Django 2.0.6 on 2018-07-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20180707_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredunit',
            name='gear_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requiredunit',
            name='rarity',
            field=models.IntegerField(default=0),
        ),
    ]
