# Generated by Django 2.0.6 on 2018-07-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20180720_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
