# Generated by Django 2.0.6 on 2018-07-23 05:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20180720_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField(default=datetime.date.today)),
                ('total_energy', models.IntegerField(default=0)),
                ('total_power', models.IntegerField(default=0)),
                ('total_chars', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Player')),
            ],
        ),
    ]
