# Generated by Django 2.0.8 on 2018-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20180723_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstat',
            options={'ordering': ['-week', 'player__player_name']},
        ),
        migrations.RemoveField(
            model_name='player',
            name='swgoh_name',
        ),
        migrations.AlterField(
            model_name='player',
            name='ally_code',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
