# Generated by Django 2.0.8 on 2018-11-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20181103_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
