# Generated by Django 2.0.8 on 2018-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20181104_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='members',
            field=models.IntegerField(default=0),
        ),
    ]
