# Generated by Django 2.0.8 on 2018-11-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_guild_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='useful_players',
            field=models.ManyToManyField(to='manager.Player'),
        ),
    ]
