# Generated by Django 2.0.8 on 2018-11-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_squad_useful_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='useful_players',
            new_name='players',
        ),
    ]
